# refer to this link for tag setup http://www.minddust.com/post/tags-and-categories-on-github-pages/
# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji
  
# Site settings
title: "Json On Rails"
description: > # this means to ignore newlines until "email:"
   Programmer Analyst, my documented journey

email: jsononrails@gmail.com
#blog logo
logo: "/assets/images/logo.png"
black_umb: "/assets/images/white_umb.png"
# blog cover
cover: "/assets/images/hello_world.png"
footer_image: "/assets/images/cover.jpg"

name: 'Json on Rails'
author: 'Jason McBride'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://jsononrails.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jsononrails
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/nomorebetz
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jsononrails
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/u/0/+JasonMcBrideOnRails/posts
    desc:	Add me on google+
    share_url: https://plus.google.com/share
    share_title: ?title=
    share_link: "&amp;url="

prose:
  rooturl: '_posts'
  siteurl: 'http://jsononrails.github.io/'
  relativeLinks: 'http://jsononrails.github.io/links.jsonp'
  media: '/assets/images/'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "summary"
        field:
          element: "text"
          label: "Summary"
          placeholder: "Enter Post Summary"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "AI"
              value: ai
            - name: "Programming"
              value: programming
            - name: "Machine Learning"
              value: machinelearning
            - name: "Interesting"
              value: interesting
            - name: "Web-Development"
              value: webdevelopment
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          placeholder: "windows.jpg"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false


include: [".htaccess"]